apiVersion: v1
kind: Service
metadata:
  name: std-service
spec:
  selector:
    app: std-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 32123
